name: 'Duplicate Issue'

on:
  issues:
    types: [labeled, unlabeled, reopened]

permissions:
  issues: write

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/support-requests@v2
        with:
          github-token: ${{ github.token }}
          support-label: 'duplicate'
          issue-comment: >
            :wave: @{issue-author}, one or more issues for this topic already exist, 
            please follow those instead of opening another one. Use the search function 
            to find issues related to your troubles. Thank you!
          close-issue: true
          lock-issue: true
          issue-lock-reason: 'off-topic'