name: 'Fix shipped with Release'

on:
  issues:
    types: [labeled, unlabeled, reopened]

permissions:
  issues: write

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/support-requests@v2
        with:
          github-token: ${{ github.token }}
          support-label: 'fix-shipped'
          issue-comment: >
            This issues' topic has been resolved and an update has been published. 
            Please check out the Releases page for a new version.
          close-issue: true
          lock-issue: false
          issue-lock-reason: 'off-topic'